#!/bin/sh

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo -e "Device flash helper scrip:"
  echo -e "$ flashall [options]\n"
  echo -e "Script assumes fastboot being available in the path"
  echo -e "By default only partitions essential to boot are re-flashed"
  echo -e "\t\tboot_ra, ubuntu-seed, snapbootsel(bak), snaprecoverysel(bak)"
  echo -e "\nOptional parameters:"
  echo -e "\t-f | --full: repartition the storage, but do not erase ubuntu-save partition"
  echo -e "\t-H | --hard-reset: same as full + format of ubuntu-save partition"
  echo -e "\t-r | --reboot: reboot device when flashing is completed"
  echo -e "\t-s | --sec <sec.elf file name>: flash passed file to sec partition."
  echo -e "\t\t!!!!Attention: This will likely blow fuses on  your board!!!!!!"
  echo -e "\t-h | --help: this help"
  exit
fi

unset FORMAT REBOOT
while [ "$1" != "" ]; do
    case $1 in
        -f | --repartition)
            REPARTITION="true"
            ;;
        -H | --hard-reset)
            echo "!!!!! Device will be completely erased prior to flashing !!!!!"
            REPARTITION="true"
            FORMAT_HARD="true"
            ;;
        -r | --reboot)
            REBOOT="true"
            ;;
        -s | --sec)
            if [ -e "${2}" ]; then
              SEC_ELF="${2}"
            else
              echo -e "Sec file [${2}] does not exist, pass correct file name!"
              exit
            fi
            shift
            ;;
        --help | -h)
            print_usage
            exit
            ;;
        *)
            # check if this is model assertion
            echo "Unknown parameter '$1'"
            print_usage
            exit
            ;;
    esac
    shift
done

# by default do not flash new partition, only reflash
if [ "${REPARTITION}" = "true" ]; then
  echo "Repartitioning..."
  fastboot flash partition:0 gpt_both0.bin
  fastboot flash partition:1 gpt_both1.bin
  fastboot flash partition:2 gpt_both2.bin
  fastboot flash partition:3 gpt_both3.bin
  fastboot flash partition:4 gpt_both4.bin
  fastboot flash partition:5 gpt_both5.bin

  ## lun 1
  fastboot flash xbl xbl.elf

  ## lun 2
  fastboot flash xblbak xbl.elf

  ## lun 3
  fastboot flash cdt sbc_1.0_8096.bin

  ## lun 4
  # a partitions
  fastboot flash rpm rpm.mbn
  fastboot flash tz tz.mbn
  fastboot flash hyp hyp.mbn
  fastboot flash pmic pmic.elf
  fastboot flash aboot emmc_appsboot.mbn
  fastboot flash devcfg devcfg.mbn
  fastboot flash cmnlib64 cmnlib64.mbn
  fastboot flash cmnlib cmnlib.mbn
  fastboot flash keymaster keymaster.mbn
  # b partitions
  fastboot flash rpmbak rpm.mbn
  fastboot flash tzbak tz.mbn
  fastboot flash hypbak hyp.mbn
  fastboot flash pmicbak pmic.elf
  fastboot flash abootbak emmc_appsboot.mbn
  fastboot flash devcfgbak devcfg.mbn
  fastboot flash cmnlib64bak cmnlib64.mbn
  fastboot flash cmnlibbak cmnlib.mbn
  fastboot flash keymasterbak keymaster.mbn
  # non a/b partitions
  ## lun 5
fi

if [ -n "${SEC_ELF}" ]; then
  echo "!!! Flashing sec partition with ${SEC_ELF} !!!"
  fastboot flash sec ${SEC_ELF}
fi

# Ubuntu partitions
echo "Cleaning boot critical partitions"
fastboot erase ubuntu-boot
fastboot erase ubuntu-data
if [ "${FORMAT_HARD}" = "true" ]; then
  fastboot erase ubuntu-save
fi

echo "Flashing Ubuntu images"
fastboot flash boot_ra boot.img
fastboot flash snaprecoverysel snaprecoverysel.bin
fastboot flash snaprecoveryselbak snaprecoverysel.bin
fastboot flash snapbootsel snapbootsel.bin
fastboot flash snapbootselbak snapbootsel.bin
fastboot flash ubuntu-seed ubuntu-seed.img

if [ "${REBOOT}" = "true" ]; then
  fastboot reboot
fi
