#!/bin/sh

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
  echo -e "Device flash helper scrip:"
  echo -e "$ flashall [options]\n"
  echo -e "Script assumes fastboot being available in the path"
  echo -e "By default only partitions essential to boot are re-flashed"
  echo -e "\t\tboot_ra, ubuntu-seed, snapbootsel(bak), snaprecoverysel(bak)"
  echo -e "\nOptional parameters:"
  echo -e "\t-f | --full: repartition emmc, but do not erase ubuntu-save partition"
  echo -e "\t-H | --hard-reset: same as full + format of ubuntu-save partition"
  echo -e "\t-r | --reboot: reboot device when flashing is completed"
  echo -e "\t-h | --help: this help"
  exit
fi
unset FORMAT REBOOT
while [ "$1" != "" ]; do
    case $1 in
        -f | --repartition)
            REPARTITION="true"
            ;;
        -H | --hard-reset)
            echo "!!!!! Device will be completely erased prior to flashing !!!!!"
            REPARTITION="true"
            FORMAT_HARD="true"
            ;;
        -r | --reboot)
            REBOOT="true"
            ;;
        --help | -h)
            print_usage
            exit
            ;;
        *)
            # check if this is model assertion
            echo "Unknown parameter '$1'"
            print_usage
            exit
            ;;
    esac
    shift
done

# by default do not flash new partition, only reflash
if [ "${REPARTITION}" = "true" ]; then
  echo "Repartitioning..."
  fastboot flash partition:0 gpt_both0.bin
  fastboot flash partition:1 gpt_both1.bin
  fastboot flash partition:2 gpt_both2.bin
  fastboot flash partition:3 gpt_both3.bin
  fastboot flash partition:4 gpt_both4.bin
  fastboot flash partition:5 gpt_both5.bin

  fastboot erase ddr

  fastboot flash cdt sbc_1.0_8096.bin
  fastboot flash xbl xbl.elf
  fastboot flash xblbak xbl.elf
  fastboot flash rpm rpm.mbn
  fastboot flash rpmbak rpm.mbn
  fastboot flash tz tz.mbn
  fastboot flash tzbak tz.mbn
  fastboot flash hyp hyp.mbn
  fastboot flash hypbak hyp.mbn
  fastboot flash pmic pmic.elf
  fastboot flash pmicbak pmic.elf
  fastboot flash aboot emmc_appsboot.mbn
  fastboot flash abootbak emmc_appsboot.mbn
  fastboot flash devcfg devcfg.mbn
  fastboot flash devcfgbak devcfg.mbn
  fastboot flash cmnlib64 cmnlib64.mbn
  fastboot flash cmnlib64bak cmnlib64.mbn
  fastboot flash cmnlib cmnlib.mbn
  fastboot flash cmnlibbak cmnlib.mbn
  fastboot flash keymaster keymaster.mbn
  fastboot flash keymasterbak keymaster.mbn
  [ -e sec.dat ] && fastboot flash sec sec.dat
fi

echo "Cleaning boot critical partitions"
fastboot erase boot_ra
fastboot format ubuntu-data
fastboot erase snapbootsel
fastboot erase snapbootselbak
fastboot erase snaprecoverysel
fastboot erase snaprecoveryselbak
if [ "${FORMAT_HARD}" = "true" ]; then
  fastboot erase ubuntu-save
fi

echo "Flashing Ubuntu images"
fastboot flash boot_ra boot-db820c.img
fastboot flash snaprecoverysel snaprecoverysel.bin
fastboot flash snaprecoveryselbak snaprecoverysel.bin
fastboot flash snapbootsel snapbootsel.bin
fastboot flash snapbootselbak snapbootsel.bin
fastboot flash ubuntu-seed ubuntu-seed.img

if [ "${REBOOT}" = "true" ]; then
  fastboot reboot
fi
