name: ifc6640
version: 18-1
summary: IFC6640 support package
description: |
 Support files for booting Inforce IFC6640
type: gadget

base: core18

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

parts:
    prebuilt:
        plugin: dump
        source: prebuilt
        organize:
            '*': blobs/

    snap-boot-sel-env:
        plugin: nil
        source: snap-boot-sel
        source-type: local
        override-pull: |
            snapcraftctl pull
            wget https://raw.githubusercontent.com/snapcore/snapd/master/include/lk/snappy_boot_common.h
            wget https://raw.githubusercontent.com/snapcore/snapd/master/include/lk/snappy_boot_v1.h
        override-build: |
            gcc lk-boot-env.c -I/usr/include/ -o lk-boot-env
            # configure initial boot environment
            ./lk-boot-env --write ${SNAPCRAFT_PART_INSTALL}/snapbootsel.bin \
                          --bootimg-file boot-ifc6640.img \
                          $( ./parse-yaml.sh ${SNAPCRAFT_PROJECT_DIR}/gadget.yaml )
            ln -sf snapbootsel.bin ${SNAPCRAFT_PART_INSTALL}/lk.conf

    arm-eabi-4-8:
        plugin: dump
        source: git://codeaurora.org/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8.git
        source-depth: 1
        source-tag: LA.BR.1.1.3.c4-01000-8x16.0
        organize:
            '*': arm-eabi-4.8/
        prime:
            - -*

    signlk:
        plugin: dump
        source: https://git.linaro.org/landing-teams/working/qualcomm/signlk.git
        source-depth: 1
        source-type: git
        prime:
            - -*

    partitioning-tool:
        plugin: dump
        source: https://github.com/kubiko/partitioning_tool.git
        source-depth: 1
        source-type: git
        organize:
            LICENSE: LICENSE_for_ptool
        prime:
            - -*
