name: ifc6640
version: 18-1
summary: IFC6640 support package
description: |
 Support files for booting Inforce IFC6640
type: gadget

base: core18

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

parts:
    prebuilt:
        plugin: dump
        source: prebuilt
        organize:
            '*': blobs/

    arm-eabi-4-8:
        plugin: dump
        source: git://codeaurora.org/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8.git
        source-depth: 1
        source-tag: LA.BR.1.1.3.c4-01000-8x16.0
        organize:
            '*': arm-eabi-4.8/
        prime:
            - -*

    signlk:
        plugin: dump
        source: https://git.linaro.org/landing-teams/working/qualcomm/signlk.git
        source-depth: 1
        source-type: git
        prime:
            - -*
