name: ifc6640
version: 18-1
summary: IFC6640 support package
description: |
 Support files for booting Inforce IFC6640
type: gadget

base: core18

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

parts:
    prebuilt:
        plugin: dump
        source: prebuilt
        organize:
            '*': blobs/

